version: "2.4"
services:
  
  db:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL
      - MYSQL_DATABASE=openfabric_db
      - MYSQL_USER=openfabric_db
      - MYSQL_PASSWORD=1qaz!QAZ
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"

  db-privileges:
    image: mysql/mysql-server
    command: mysql -u root -pMySQL --host db -e "GRANT ALL PRIVILEGES ON *.* TO 'openfabric_db'"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      
  backend:
    image: product-browser-back
    build:
      context: ./backend
    expose:
      - "3000"
    depends_on: 
      db:
        condition: service_healthy
    links:
      - db

  backend-migrate:
    image: product-browser-back
    command: npx prisma migrate dev --name init
    depends_on:
      - backend
 
  frontend:
    image: product-browser-front
    build:
      context: ./front
    ports:
      - "4200:80"
    depends_on: 
      - backend
    links:
      - backend
